# Generated by Django 5.2.4 on 2025-08-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_equipo_logo_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calificacion',
            old_name='comentario',
            new_name='descripcion_larga',
        ),
        migrations.AddField(
            model_name='calificacion',
            name='descripcion_corta',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
