# Generated by Django 5.2.4 on 2025-08-21 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_comentario_calificacion_descripcion_larga_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partido',
            name='equipo_local',
        ),
        migrations.RemoveField(
            model_name='partido',
            name='equipo_visitante',
        ),
        migrations.RemoveField(
            model_name='partido',
            name='liga',
        ),
        migrations.DeleteModel(
            name='Calificacion',
        ),
        migrations.DeleteModel(
            name='Partido',
        ),
    ]
