# Generated by Django 5.2.4 on 2025-08-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='descripcion_corta',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
